name: Solana Production CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Deployment environment'
        required: true
        default: 'devnet'
        type: choice
        options:
        - devnet
        - testnet
        - mainnet

env:
  CARGO_TERM_COLOR: always
  NODE_VERSION: 20
  RUST_VERSION: stable
  ANCHOR_VERSION: 0.29.0
  SOLANA_VERSION: 1.18.22

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      programs: ${{ steps.changes.outputs.programs }}
      clients: ${{ steps.changes.outputs.clients }}
      tests: ${{ steps.changes.outputs.tests }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - name: Detect changes
      id: changes
      run: |
        echo "programs=$(git diff --name-only HEAD~1 HEAD | grep -E '^programs/' | wc -l)" >> $GITHUB_OUTPUT
        echo "clients=$(git diff --name-only HEAD~1 HEAD | grep -E '^(app|client|web)/' | wc -l)" >> $GITHUB_OUTPUT
        echo "tests=$(git diff --name-only HEAD~1 HEAD | grep -E '^tests/' | wc -l)" >> $GITHUB_OUTPUT

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
    
    - name: Install cargo-audit
      run: cargo install cargo-audit
    
    - name: Rust Security Audit
      run: cargo audit
    
    - name: Setup Node.js for security scan
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: NPM Security Audit
      run: npm audit --audit-level high
    
    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD

  lint-and-format:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
        components: rustfmt, clippy
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Rust format check
      run: cargo fmt --all -- --check
    
    - name: Rust clippy
      run: cargo clippy --all-targets -- -D warnings
    
    - name: JavaScript/TypeScript lint
      run: npm run lint
    
    - name: TypeScript type check
      run: npm run type-check

  build-programs:
    name: Build Programs
    runs-on: ubuntu-latest
    needs: [detect-changes]
    if: needs.detect-changes.outputs.programs > 0 || github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Install Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
    
    - name: Install Anchor CLI
      run: npm install -g @coral-xyz/anchor-cli@${{ env.ANCHOR_VERSION }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build programs
      run: anchor build --arch sbf
    
    - name: Upload program artifacts
      uses: actions/upload-artifact@v3
      with:
        name: program-artifacts
        path: |
          target/deploy/
          target/idl/
          target/types/

  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [build-programs]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
    
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run Rust unit tests
      run: cargo test --workspace

  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [build-programs]
    strategy:
      matrix:
        test-suite: [basic, advanced, edge-cases]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
    
    - name: Install Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
    
    - name: Install Anchor CLI
      run: npm install -g @coral-xyz/anchor-cli@${{ env.ANCHOR_VERSION }}
    
    - name: Download program artifacts
      uses: actions/download-artifact@v3
      with:
        name: program-artifacts
        path: target/
    
    - name: Install dependencies
      run: npm ci
    
    - name: Start local test validator
      run: |
        solana-test-validator --reset --quiet &
        sleep 10
    
    - name: Run integration tests
      run: npm run test:integration:${{ matrix.test-suite }}
      env:
        TEST_SUITE: ${{ matrix.test-suite }}

  performance-test:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: [build-programs]
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup performance testing environment
      run: |
        echo "Setting up performance testing..."
        # Add performance test setup here
    
    - name: Run performance benchmarks
      run: |
        echo "Running performance tests..."
        # Add performance testing commands here
    
    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: performance-results.json

  build-client:
    name: Build Client Applications
    runs-on: ubuntu-latest
    needs: [detect-changes, build-programs]
    if: needs.detect-changes.outputs.clients > 0 || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        client: [web, mobile, cli]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Download program artifacts
      uses: actions/download-artifact@v3
      with:
        name: program-artifacts
        path: target/
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build ${{ matrix.client }} client
      run: npm run build:${{ matrix.client }}
    
    - name: Upload client artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.client }}-client
        path: dist/${{ matrix.client }}/

  deploy-devnet:
    name: Deploy to Devnet
    runs-on: ubuntu-latest
    needs: [security-scan, lint-and-format, test-unit, test-integration]
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_environment == 'devnet')
    environment: devnet
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup deployment environment
      run: |
        echo "SOLANA_NETWORK=devnet" >> $GITHUB_ENV
        echo "RPC_URL=https://api.devnet.solana.com" >> $GITHUB_ENV
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
    
    - name: Install Anchor CLI
      run: npm install -g @coral-xyz/anchor-cli@${{ env.ANCHOR_VERSION }}
    
    - name: Download program artifacts
      uses: actions/download-artifact@v3
      with:
        name: program-artifacts
        path: target/
    
    - name: Configure Solana CLI
      run: |
        solana config set --url $RPC_URL
        solana config set --keypair /tmp/deploy-keypair.json
        echo '${{ secrets.DEVNET_DEPLOY_KEY }}' > /tmp/deploy-keypair.json
        chmod 600 /tmp/deploy-keypair.json
    
    - name: Airdrop SOL for deployment
      run: |
        solana airdrop 2 --commitment confirmed
        sleep 5
    
    - name: Deploy programs
      run: |
        anchor deploy --network devnet --program-keypair /tmp/deploy-keypair.json
    
    - name: Save program IDs
      run: |
        anchor keys list > deployment-info.txt
        echo "## Devnet Deployment" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        cat deployment-info.txt >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
    
    - name: Run post-deployment tests
      run: npm run test:post-deploy
      env:
        SOLANA_NETWORK: devnet
    
    - name: Cleanup sensitive files
      if: always()
      run: |
        rm -f /tmp/deploy-keypair.json

  deploy-testnet:
    name: Deploy to Testnet
    runs-on: ubuntu-latest
    needs: [deploy-devnet, performance-test]
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_environment == 'testnet')
    environment: testnet
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to Testnet
      run: |
        echo "Deploying to testnet with enhanced security checks..."
        # Add testnet deployment logic with additional safety measures
    
    - name: Verify testnet deployment
      run: |
        echo "Verifying testnet deployment..."
        # Add verification steps

  deploy-mainnet:
    name: Deploy to Mainnet
    runs-on: ubuntu-latest
    needs: [deploy-testnet]
    if: github.ref == 'refs/heads/main' && (contains(github.event.head_commit.message, '[deploy:mainnet]') || (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_environment == 'mainnet'))
    environment: mainnet
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Manual approval check
      run: |
        echo "⚠️  MAINNET DEPLOYMENT INITIATED"
        echo "This is a production deployment to Solana mainnet."
        echo "Ensure all tests have passed and security reviews are complete."
    
    - name: Deploy to Mainnet
      run: |
        echo "Deploying to mainnet with maximum security..."
        # Add mainnet deployment with comprehensive safety checks
    
    - name: Post-deployment verification
      run: |
        echo "Running comprehensive post-deployment verification..."
        # Add extensive verification and monitoring setup
    
    - name: Notification
      if: always()
      run: |
        status="${{ job.status }}"
        if [ "$status" = "success" ]; then
          echo "✅ Mainnet deployment successful!"
        else
          echo "❌ Mainnet deployment failed!"
        fi
        # Add Discord/Slack/Telegram notification logic

  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    needs: [build-programs]
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Download program artifacts
      uses: actions/download-artifact@v3
      with:
        name: program-artifacts
        path: target/
    
    - name: Generate IDL documentation
      run: |
        npm run docs:generate
    
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build

  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    needs: [deploy-devnet, deploy-testnet, deploy-mainnet]
    if: always()
    steps:
    - name: Cleanup deployment artifacts
      run: |
        echo "Cleaning up temporary deployment files..."
        # Add cleanup logic for sensitive deployment artifacts