# Example: Basic Anchor Project CI/CD
# Copy this file to .github/workflows/ci.yml in your Anchor project

name: Basic Anchor CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  SOLANA_VERSION: "1.18.26"
  ANCHOR_VERSION: "0.30.1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js for tests
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Setup Solana CLI
      - name: Setup Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      # Setup Rust toolchain
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # Setup Anchor CLI
      - name: Setup Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --locked --force

      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ~/.cache/solana
            node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/Cargo.lock', '**/package-lock.json') }}

      # Install npm dependencies
      - name: Install dependencies
        run: npm ci

      # Configure Solana CLI
      - name: Configure Solana
        run: |
          solana config set --url localhost
          solana-keygen new --no-bip39-passphrase --silent

      # Build programs
      - name: Build programs
        run: anchor build

      # Start local validator
      - name: Start validator
        run: |
          solana-test-validator --detach --reset --quiet
          timeout 30s bash -c 'until solana cluster-version; do sleep 1; done'

      # Run tests
      - name: Run tests
        run: anchor test --skip-local-validator

  # Optional: Deploy to devnet on main branch pushes
  deploy-devnet:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    environment: devnet
    steps:
      - uses: actions/checkout@v4

      # Setup tools (same as above)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --locked --force

      - name: Install dependencies
        run: npm ci

      # Setup deployment wallet
      - name: Setup deployment wallet
        env:
          DEPLOY_WALLET_SECRET: ${{ secrets.DEPLOY_WALLET_SECRET }}
        run: |
          echo "$DEPLOY_WALLET_SECRET" > deploy-wallet.json
          solana config set --keypair deploy-wallet.json
          solana config set --url https://api.devnet.solana.com

      # Build and deploy
      - name: Build and deploy
        run: |
          anchor build
          anchor deploy --provider.cluster devnet

      # Clean up secrets
      - name: Clean up
        if: always()
        run: rm -f deploy-wallet.json